version: '3'

services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        entrypoint: "/code/entrypoint.sh"
        volumes:
            - ./:/code/
        ports:
            - "8000:8000"
        env_file:
            - ./.env
        depends_on:
            - db

    db:
        image: postgres
        volumes:
            - ./postgres_data:/var/lib/postgresql
        environment:
            POSTGRES_HOST_AUTH_METHOD: "trust"
        env_file:
            - ./.env


volumes:
    postgres_data:
